### ISSUE TITLE
Issue with host name containing special characters

### ISSUE THREAD

**Issue by smuribi** [mjtrangoni/flexlm_exporter#3]
Hi there, finding this exporter very useful.  We are seeing some strangeness though with server names containing a dash (i.e. my-host@domain.com).  It seems as though everything after the "my" is truncated.  

Thanks!

Salem

**Comment by mjtrangoni** [comment]
Hi @smuribi,
Thanks for reporting! This should be fixed now. Could you please confirm it?

**Comment by smuribi** [comment]
Thanks Mario, that works! I did have a question though, can the exported handle multiple products in the same license.dat file or do i need to run multiple exporters?

# FlexLM Licenses to be monitored.
---
licenses:
  - name: MOSEKLM
    license_file: /opt/MATLAB_FlexLM/R2016b/etc/license.dat
    license_server: 27001@talicense
    monitor_users: True
    monitor_reservations: True
licenses:
  - name: MLM
    license_file: /opt/MATLAB_FlexLM/R2016b/etc/license.dat
    license_server: 27001@talicense
    monitor_users: True
    monitor_reservations: True

**Comment by mjtrangoni** [comment]
Hi @smuribi,

Yes, you can check all your licenses with only one flexlm_exporter instance. The only one *requirement* is that all flexlm server have to be reachable (network).

You don't have to define `license_file` and `license_server` at the same time, one of them is enough. 

For example,

```
licenses:
  - name: MOSEKLM
    license_file: /opt/MATLAB_FlexLM/R2016b/etc/license.dat
    monitor_users: True 
    monitor_reservations: True
    licenses:
  - name: MLM
    license_server: 27001@talicense
    monitor_users: True
    monitor_reservations: True
```
