### ISSUE TITLE
Add features_to_include option for readability and convenience

### ISSUE THREAD

**Issue by VonOx** [mjtrangoni/flexlm_exporter#6]
Hello !

For those using combined licence file ( multiple vendors and features ) it is a pain to edit and maintain yml config file because a lot of feature must be excluded

exemple:

```yaml
licenses:
  - name: Keyshot
    license_server: PORT@SERVER
    features_to_exclude: FlowmasterV7X,DENIED_INFOV7,IMINSPECT,IMALIGN,IM_PROE,VCAST_VCDB_0700,VCAST_VCSHELL_0700,VCAST_VPYTHON_0700,CCAST_0767,CCAST_0702,CCAST_0701,TQ_CADFIX_SOLIDWORKS,TQ_CADFIX_PROE,TQ_CADFIX_IGES,TQ_CADFIX_STEP,TQ_CONVERTISSEUR_CAO_SAT,CETIM_TQ_COMPARAISON,CETIM_TQ_CHIFFRAGE,CETIM_TQ_OP_1_PARAM,CETIM_TQ_SOUS_TRAIT,CETIM_TQ_TOLERIE,CETIM_TQ_EBAVURAGE,CETIM_TQ_RECTIF,CETIM_TQ_TOURNAGE,CETIM_TQ_INTERFACE_SW,CETIM_FOREIGN_LANGUAGE_VERSION,CETIM_ACIS_MFG_VIEW,CETIM_DEVIS,CETIM-COBRA-DATA-ADMIN,CETIM-COBRA-NFE250302,CETIM-COBRA-VDI-2014,CETIM-COBRA-VDI-1986,CETIM-COBRA
    monitor_users: True
    monitor_reservations: False
```

Can be

```yaml
licenses:
  - name: Keyshot
    license_server: PORT@SERVER
    features_to_include: keyshot_vr,keyshot2
    monitor_users: True
    monitor_reservations: False
```

What do you think ?

Also vendor can be filtered ( maybe ? )

Thank you
Vincent.
