### ISSUE TITLE
Issue with multiple licenses (license aggregation) in the same name field

### ISSUE THREAD

**Issue by babainc** [mjtrangoni/flexlm_exporter#61]
Hello,
I've a lack of metrics when multiple licenses are set in the same "name" field (namespace). Here is the licenses.yaml for a better understanding

```
 FlexLM Licenses to be monitored.
---
licenses:
  - name: questasim
    license_server: 1717@server-E1-X4,1718@server-E1-X4
    features_to_include: msimviewer,msimdataflow,msimhdlsim,msimhdlmix,msimcoverage
    monitor_users: True
    monitor_reservations: True
    monitor_versions: True
```
The system is running on a Debian11 linux server and the flexlm_exporter container use the latest docker version.
this container is started from a dockerfile that start also node_explorer (linux), blackbox_exporter, alertmanager, prometheus, graphana to monitor linux server activited and now the flexlm licenses activities ;) 

### What did you expect to see?
In this usecase, there is two licenses in the "questasim" namespace. These two licenses are on different port (1717 and 1718) and in my case the license are really close, so we have almost same token list and almost the same amount of seat per token.

### What did you see instead?
I see only the first license (1717@server-E1-X4), the second one (1718@server-E1-X4) is not detected or has no metrics. If I split each licenses into differents "name" field (ie questasim1717 and questasim1718), both are properly detected with the correct token list and seat.
I use the graphana dashboard proposed in your markdown, and I see the number of seat for only one license (and due to license activities reported, I know that it is the first one that is processed). In graphana, the row indicating the server status and vendor status field show also only see one lines where I expected to see 2 lines one per listen port (to perform license port/nae distinction) 

### What did you expect?
In case of license aggregation on the same name, there is no information in the collected metrics indicating the license targeted, that can be separate easily (in my case) with the listening port 1717 or 1718.

We can consider the following usecase: IT want to aggregate multiple licenses in the same namespace (because it is the same software), to manage the token of this software at a batch level. So It would be nice to sum seat from duplicate token. Maybe this kind of computation can be done under a graphana panel but I don't know if it will be possible to do it easily in alertmanager.
