### ISSUE TITLE
List of servers in license_server on windows

### ISSUE THREAD

**Issue by avelure** [mjtrangoni/flexlm_exporter#64]
On windows the `lmutil lmstat -c` command accepts a list of servers separated by `;`. The documentation for flexlm_exporter displays servers separated by a comma in the yaml file for `license_server`. The value of the key is passed directly to lmstat without formatting, which works on Linux, but not Windows as then only the first server is processed. A proposal is to substitute whichever separator is in the `license_server` key with what is the appropriate for the OS.

### flexlm_exporter command line flags and relevant YAML configuration file information
--path.lmutil
```yaml
licenses:
  - name: app
    license_server: 1902@SERVER,1903@SERVER
    monitor_users: True
    monitor_reservations: True
    monitor_versions: False
```

### Are you running flexlm_exporter in Docker?
No

### What did you do that produced an error?
Created yaml file according to Readme.md

### What did you expect to see?
Both servers show up in data output

### What did you see instead?
Only first server
