### ISSUE TITLE
Incorrect server status

### ISSUE THREAD

**Issue by VonOx** [mjtrangoni/flexlm_exporter#7]
### Host operating system: output of `uname -a`

Prometheus / Grafana : Ubuntu 16.04
Flexlm: Server 2012R2

### flexlm_exporter version: output of `flexlm_exporter --version`
Latest Docker image

### What did you expect to see?

My server is UP and Running in dashboard

### What did you see instead?

Server down 

![capture](https://user-images.githubusercontent.com/1528694/40042628-59dbc730-5822-11e8-9239-00ff8c30c87f.PNG)

I think this is triad configuration related and data parsing. I have only one server

```yaml
  - name: Creo
    license_server: 7788@BVS15004
    features_to_exclude: PROBUNDLE_10118,PROBUNDLE_10119,14,247,294,254,255,256,257,137,247,48,54,57,61,127,191,PROBUNDLE_10105,PROBUNDLE_10107,89,157,161,211,212,ILINK_TK_ACCESS_License,ILINK_CLIENT_License,MECMOTENG_MO,CREOSCHEM_Lite,MECMOTUI_MO,RSDESIGNER_Lite,10105,10107,10118,10119
    monitor_users: True
    monitor_reservations: True
```
