### ISSUE TITLE
Install-Manual for Windows-Server-Environment/lmstat="collector failed after:"

### ISSUE THREAD

**Issue by plustig73** [mjtrangoni/flexlm_exporter#82]
Hallo,

is there anywhere a install-manual or instructions how the flexlm_exporter should be installed or used in a Windows-SErver-Environment? 

Prometheus is running on the license server, grafana is also running. but i am not able to get the license-Informations to Prometheus :(

Maybe someone can help me.

Thanks a lot.

'BR

Roland

**Comment by plustig73** [comment]
Hello, I think I have made a step forward. 

The FlexLM_exporter is now running and transmitting data to Prometheus.

Unfortunately, no meaningful data arrives yet. The following messages are generated:

```
level=debug ts=2023-10-16T12:43:30.641Z caller=flexlm_exporter.go:88 msg="collect query:" filters="unsupported value type"
level=error ts=2023-10-16T12:43:30.705Z caller=collector.go:173 lmstat="collector failed after:" 0.0010003=:
level=debug ts=2023-10-16T12:43:30.705Z caller=collector.go:177 OK:=lmstat_feature_exp collectorsucceededafter:=0.0010003
```

Especially the "lmstat="collector failed after" still worries me. 

In Prometheus this arrives:

```
# HELP flexlm_exporter_build_info A metric with a constant '1' value, identified by version, revision, branch and goversion, from which flexlm_exporter was built.
# TYPE flexlm_exporter_build_info gauge
flexlm_exporter_build_info{branch="",goversion="go1.19",revision="",version=""} 1
# HELP flexlm_scrape_collector_duration_seconds flexlm_exporter: Duration of a collector scrape.
# TYPE flexlm_scrape_collector_duration_seconds gauge
flexlm_scrape_collector_duration_seconds{collector="lmstat"} 0.0009984
flexlm_scrape_collector_duration_seconds{collector="lmstat_feature_exp"} 0
# HELP flexlm_scrape_collector_success flexlm_exporter: Whether a collector was successful.
# TYPE flexlm_scrape_collector_success gauge
flexlm_scrape_collector_success{collector="lmstat"} 0
flexlm_scrape_collector_success{collector="lmstat_feature_exp"} 1
# HELP flexlm_scrape_error flexlm_exporter: Whether an error occurred while scrapping a licence.
# TYPE flexlm_scrape_error gauge
flexlm_scrape_error{collector="lmstat_feature_exp",name="SolidWorks"} 1
# HELP promhttp_metric_handler_errors_total Total number of internal errors encountered by the promhttp-metric handler.
# TYPE promhttp_metric_handler_errors_total Counter
promhttp_metric_handler_errors_total{cause="encoding"} 0
promhttp_metric_handler_errors_total{cause="gathering"} 0
```

The Licenses.yml looks like this:

```
# FlexLM licenses to be monitored.
---
Licenses:
  - Name: SolidWorks
    license_server: 123456@server001
    include_features: solidworks
    monitor_users: True
    monitor_reservations: True
    monitor_versions: False

```
The Prometheus.yml thus:

```
# my global configuration
global:
  scrape_interval: 60s # Sets the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Rules are evaluated every 15 seconds. Default is every 1 minute.
  # scrape_timeout is set to the global default value (10s).

# alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - Targets:
          # - alertmanager:9093

# Load rules once and evaluate periodically according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration that contains exactly one endpoint to be scrapped:
# Here it is Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to each time series queried by this configuration.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'.
    # schema defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
      - targets: ["localhost:9319"]
```

I start the FlexLM exporter via a batch file:

`flexlm_exporter.exe --path.lmutil="C:\Program Files (x86)\SOLIDWORKS SolidNetWork License Manager\utils" --collector.lmstat --web.listen-address=":9319" --path.config="D:\Source\FlexLM_Exporter\licenses.yml" --log.level=debug --web.disable-exporter-metrics
`
What could be the reason that the licenses are not read?

Regards
